LPS-134473 - There is a UI inconsistency in the Select Page modal
liferay-immersion/liferay-portal pull request #30
Opened 2022-05-10 19:46 UTC by M-IgorFranca

2022-05-10 19:46 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-10 19:46 UTC, M-IgorFranca commented
ci:test:sf

2022-05-10 19:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8fa7d8bc2ad2058a2a7378f88ef33ae38b5a3619">8fa7d8bc2ad2058a2a7378f88ef33ae38b5a3619</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/M-IgorFranca/liferay-portal/tree/LPS-134473">LPS-134473</a><br/>Branch GIT ID: <a href="https://github.com/M-IgorFranca/liferay-portal/commit/845de82592758debcd93c13a06b537be797c8c16">845de82592758debcd93c13a06b537be797c8c16</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2559/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2559/jenkins-report.html">here</a>.</h5></details></html>

2022-05-10 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2559/">test-portal-source-format#2559</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2559/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1791262451">[master] ci:test:sf - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-05-10[12:47:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/9169/">publish-testray-report#9169</a><br/></div></div>

2022-05-11 13:36 UTC, liferay-immersion commented
ci:test:relevant

2022-05-11 13:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/3394/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3394/jenkins-report.html">here</a>.</b></p>

2022-05-11 17:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/3394/">test-portal-acceptance-pullrequest(master)#3394</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3394/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1803120306">[master] ci:test:relevant - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-05-11[06:36:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/9505/">publish-testray-report#9505</a><br/></div></div>

2022-05-13 20:44 UTC, rebsilva requested changes
Hi @M-IgorFranca! I left some comments and suggestions, but feel free to express your thoughts too! The links I mentioned about the `!important` tag:

- [CSS !important: Don’t Use It. Do This Instead ](https://uxengineer.com/css-specificity-avoid-important-css/)
- [When Using !important is The Right Choice](https://css-tricks.com/when-using-important-is-the-right-choice/)
- [CSS The !important Rule](https://www.w3schools.com/css/css_important.asp)

2022-05-13 20:44 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +			height: auto !important;
I noticed that you used some `!important` tags in your code, usually we avoid that since it's not a good practice; we use it in specific cases when there is no other way around. I will leave some links above about this to help you making a solution without using it; If you think using `!important` is the only way, could you explain me why? Thanks!

2022-05-13 20:44 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +				height: auto !important;
Same about the first `!important` comment above

2022-05-13 20:44 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +	position: fixed !important;
Same about the first `!important` comment above

2022-05-13 20:44 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Could you explain why you had to change all the `<a>` tags into `<span>` tags?

2022-05-14 02:21 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
I changed it because I didn't see the need for these texts to be a link. I saw two possibilities, change HTML structure or modify CSS properties, color, mouse cursor and underline. I don't understand why these texts have an empty href="javascript. Can you explain to me why most texts have an "a" tag?

2022-05-14 15:28 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +			height: auto !important;
I used some important tags because I find a lot of styles within HTML. I know where the HTML is implemented, but the styles aren't there. Another file manipulated this HTML and placed CSS styles inside it. I can't find where this happens, and the only way I've seen to solve this is using !important tag. But I will continue to look for where these changes are happening.

2022-05-14 15:29 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +	position: fixed !important;
Thanks for the links with the css specificity explanations, this will help me not need to use the !important tag here. In this case another more specific css file is winning. I just need to calculate the specificity level and advance one more level.

2022-05-16 17:29 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +	position: fixed !important;
The class that override my position is: 
.modal-dialog:not(.dialog-iframe-modal):not(.modal-full-screen) inside the gradle-plugins-workspace.
This class have 0.0.3.0 the specificity.

I changed my class to get 0.0.3.1 the specificity. So I no longer need the !important tag in position. But I still need the !important tag at the time because I don't know where that style is defined inside the HTML tag.

2022-05-16 17:32 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +				height: auto !important;
I made modal-body more general so I don't need to call `height: auto !important;` 2 times.

2022-05-16 18:09 UTC, M-IgorFranca commented
ci:test:sf

2022-05-16 18:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3808/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3808/jenkins-report.html">here</a>.</b></p>

2022-05-16 18:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/648de36a734019adfafb1aa8525cf21a5afc5459">648de36a734019adfafb1aa8525cf21a5afc5459</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/M-IgorFranca/liferay-portal/tree/LPS-134473">LPS-134473</a><br/>Branch GIT ID: <a href="https://github.com/M-IgorFranca/liferay-portal/commit/5393ceb26404390d03166be71b352bf8a8dd918c">5393ceb26404390d03166be71b352bf8a8dd918c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3808/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3808/jenkins-report.html">here</a>.</h5></details></html>

2022-05-16 18:15 UTC, M-IgorFranca commented
ci:test:relevant

2022-05-16 18:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2252/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2252/jenkins-report.html">here</a>.</b></p>

2022-05-16 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3808/">test-portal-source-format#3808</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3808/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1850332512">[master] ci:test:sf - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-05-16[11:09:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/3585/">publish-testray-report#3585</a><br/></div></div>

2022-05-16 20:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 192 out of 193 jobs passed in 1 hour 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/648de36a734019adfafb1aa8525cf21a5afc5459">648de36a734019adfafb1aa8525cf21a5afc5459</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ea80da0e05e3e7949a108eeaa019b45c1dea339">8ea80da0e05e3e7949a108eeaa019b45c1dea339</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3269">Acceptance Upstream DXP (master) #3269</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7723/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7445/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15635/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/5825/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6784/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19411/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6561/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18310/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8343/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6863/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18751/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17443/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14057/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16511/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18746/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7720/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6248/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6899/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14056/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18309/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15979/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15637/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8304/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18377/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7499/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8305/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8088/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 191 out of 193 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2252/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17444/"><strike>modules-integration-mysql57-jdk8/0/6</strike></a></li></ul></li></ul></div><details><summary><strong>191 Successful Jobs:</strong></summary><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19414/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7335/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19409/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6782/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7723/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15980/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8069/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6900/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/7721/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/5826/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullreque [...]

2022-05-16 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2252/">test-portal-acceptance-pullrequest(master)#2252</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2252/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1850858090">[master] ci:test:relevant - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-05-16[11:15:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/5390/">publish-testray-report#5390</a><br/></div></div>

2022-05-16 20:50 UTC, rebsilva requested changes
Hi @M-IgorFranca, great job with your progress on this PR! Just some investigation and soon it will be good to go :tada:

2022-05-16 20:50 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
As you said the `<a>` tag usually is related to a link or in other cases to a javascript function, like:

`<a href="javascript:alert('Hello World!');">Execute JavaScript</a>`

When you click the "Execute Javascript" you will receive an alert "Hello World!". In our case we have `<a href="javascript:;">` where there is nothing after the `javascript:`, so the text will only have the appearance of a link and won't take the user to another page or make some action. My guess is that was made to look like a link because the options in the modal are **pages**, so it make sense visually for them to look like links; maybe is related to accessibility reasons too but I'm not sure. My recommendation is for you to search for previous commits on these lines to try to understand why it was made like this; after we can make a decision to change or not.

2022-05-16 20:50 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +		height: auto !important;
Its a great thing that you managed to remove two `!important` tags from your code, well done! About these two, I will discuss about with the other front ends if there is another way to do this without using it.

2022-05-16 22:19 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Hello, @M-IgorFranca,
I tested the current behavior on master and I saw that the anchor elements for `Home` and `Pages` behave as links, as shown in the attached video. I'm not sure if we can have more than one level into Home > My Page. If we had more options like: `Home > My PageOne` and `Home > My PageTwo` it could be a problem if it was not an anchor element. I think we should keep the current behavior by keeping the <a> tags or be sure that those levels cannot be created.

https://user-images.githubusercontent.com/26491796/168690160-98bc8625-9b2b-4249-a524-b9aa1b9f297a.mp4

2022-05-17 01:08 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Hello @alinedoleron, before send PR I enable the private pages in portal and created some pages, I attached this image in Jira:

![BugFixPrivatePage](https://user-images.githubusercontent.com/61854510/168705600-75883b1e-f258-4813-a50d-58b0ec155665.png)

I did the same with Private Pages disabled:

![PrivatePagesDasable](https://user-images.githubusercontent.com/61854510/168705593-cb9c3a3f-c458-4a5b-a6ac-35770837289d.png)

2022-05-17 01:29 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Hi @rebsilva, when you started investigating this bug I had no idea how this modal should look. Pedro asked if a design could help me. I received this [Mockup](https://www.figma.com/file/m3RH9sGTaODgWMpFCMjZ7V/DDL-select-page-modal?node-id=0%3A1) and tried to follow this structure. 

I thought it would be better to change the html tag, this would reduce the amount of code. But if you believe that at some point these links might be useful, I can use the `<a>` Tags and implement CSS for the tags to look like the mockup.

2022-05-17 02:04 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
> +		height: auto !important;
Okay, thanks for helping me improve!

2022-05-17 13:41 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Hi @M-IgorFranca!
@rebsilva and I tested today the cases where we have pages inside pages and how it should behave. As we can see on the video, the navigation is needed so we can reach the specific page and not only the first level. After discussing this matter with the team, we concluded that <a> tag must be kept to not to change the current behavior. 

https://user-images.githubusercontent.com/26491796/168821328-61ba67ce-3919-4cd2-8213-982052ee2373.mp4

.

2022-05-17 15:06 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Also @M-IgorFranca  can you please change your commit message to relate to what you made for the solution and not the problem? I left some recommendations [here](https://liferay.slack.com/archives/C03DE7M2HDZ/p1652795538751849), thanks!

2022-05-17 16:17 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Of course @rebsilva, I'm try to implement the navigation tab that @alinedoleron commented on. When it's done, I push my new code with the correct message, is that ok with you?

2022-05-17 16:26 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
@alinedoleron now I understand the correct behavior this modal. Thanks!

2022-05-17 16:46 UTC, rebsilva commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
Of course @M-IgorFranca, take your time and send the commit with the new message when you are done, thanks!

2022-05-17 17:17 UTC, M-IgorFranca commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js
> +			'<li class="public {publicLayoutClass}"><span>' +
To tell you the truth, this behavior was already occurring, I just needed changed the `<span>` tag for `<a>` tag for looks like a link action:

![image](https://user-images.githubusercontent.com/61854510/168872252-ff20b858-d4fc-4a09-9d9c-1d586fe2b60e.png)

2022-05-17 17:58 UTC, M-IgorFranca commented
ci:test:sf

2022-05-17 18:06 UTC, M-IgorFranca commented
ci:test:relevant

2022-05-17 18:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/3338/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3338/jenkins-report.html">here</a>.</b></p>

2022-05-17 19:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 192 out of 193 jobs passed in 1 hour 37 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47cb84a4a1472f8c51d35ecd753db4e08f88b1a8">47cb84a4a1472f8c51d35ecd753db4e08f88b1a8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b26ca2a713e852479ebbdca44c415dad7d6f928a">b26ca2a713e852479ebbdca44c415dad7d6f928a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3278">Acceptance Upstream DXP (master) #3278</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14065/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18480/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19768/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19374/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14062/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15257/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20473/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18486/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14063/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17779/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21300/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19913/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19774/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17098/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20464/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17090/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19925/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19766/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17776/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17282/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18485/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17281/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17095/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18956/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8776/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20474/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/9059/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 191 out of 193 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/3338/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/15260/"><strike>modules-integration-mysql57-jdk8/0/6</strike></a></li></ul></li></ul></div><details><summary><strong>191 Successful Jobs:</strong></summary><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8777/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/8774/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17278/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17091/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/14065/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21299/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21295/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17280/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/20468/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18963/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-port [...]

2022-05-17 19:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/3338/">test-portal-acceptance-pullrequest(master)#3338</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3338/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1852039322">[master] ci:test:relevant - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-05-17[11:06:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/9352/">publish-testray-report#9352</a><br/></div></div>

2022-07-27 23:14 UTC, rebsilva requested changes
Hey @M-IgorFranca! I know it's been a while but I came here with great news :sparkle: 

I've found a way to fix the bug without using any `important!` tag :tada: but I also discovered other problems, like when we had more than 10 pages the modal would only render the first 10; this was happening because after the U22 the private pages tab was discontinued and now we have only a "pages" tab on the modal. Logic on the `ddm_form.js` uses the private tab to make a verification to render the pages and was returning `null` (since there aren't private pages by default anymore); I can explain this better to you in person if you want.

So I've made a [solution](https://github.com/rebsilva/liferay-portal/pull/123) that consists in 3 commits:

 _LPS-134473 Fix css from select page modal of link to page field_: I used a lot from your solution, thanks a lot! I also made some changes so the `important!` prop wouldn't be necessary.
 
 _LPS-134473 Verify first if private pages tab is enabled on the select page modal_: Here I'm changing the logic to verify first if private pages are enabled to call the function (avoiding the null error).
 
_LPS-134473 Change hex colors into their respective variables_: Is a good practice to use (when possible) the variables of the colors instead of their hex code; you can see them in the `_global.scss` file.

So I suggest you to make these changes and send the solution again (can be here or you can open another PR if you want), but if you don't have the time/are busy with other things please let me know! Thanks a lot for you patience on this!

2022-07-28 21:55 UTC, M-IgorFranca commented
thanks @rebsilva , I studied your modifications and will implement them in my pr. Thank you very much!

2022-07-29 12:47 UTC, rebsilva commented
ci:test:sf

2022-07-29 12:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/2956/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2956/jenkins-report.html">here</a>.</b></p>

2022-07-29 12:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c18f95df364863fe553e48a4cd9257734ae480b9">c18f95df364863fe553e48a4cd9257734ae480b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/M-IgorFranca/liferay-portal/tree/LPS-134473">LPS-134473</a><br/>Branch GIT ID: <a href="https://github.com/M-IgorFranca/liferay-portal/commit/a7a5ddf15ca3f6f7a2417d8489bb117a049da949">a7a5ddf15ca3f6f7a2417d8489bb117a049da949</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2956/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2956/jenkins-report.html">here</a>.</h5></details></html>

2022-07-29 13:35 UTC, rebsilva approved these changes
Really good job @M-IgorFranca!! Thanks for your patience and hardwork on this! :tada:

2022-07-29 13:35 UTC, rebsilva commented
ci:test:relevant

2022-07-29 14:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2956/">test-portal-source-format#2956</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2956/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-immersion/liferay-portal/pull/30">liferay-immersion#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1930663100">[master] ci:test:sf - M-IgorFranca &gt; liferay-immersion - PR#30 - 2022-07-29[05:47:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/10963/">publish-testray-report#10963</a><br/></div></div>

2022-07-29 16:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/2169/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2169/jenkins-report.html">here</a>.</b></p>

2022-07-31 20:39 UTC, M-IgorFranca commented
ci:stop

2022-08-01 16:29 UTC, closed without merging